### PR TITLE
Feature: HsvStringColorPicker / HsvaStringColorPicker

### PR DESCRIPTION
**Pull request by RyanChristian4427**
I recently noticed that `HsvColorPIcker` was the odd one out and did not have a way to use string representations of the value. This PR adds that functionality. 

## Change Log
* Added HsvStringColorPicker & HsvaStringColorPicker components
* Added conversions to/from HSV(A)
* Added `size-limit` entries
* Added documentation to cover the new components
* Added some tests for both

### CODE REVIEW

**Comment by RyanChristian4427** [comment]
**Size Change:** +50 B (1%) 

**Total Size:** 2.74 kB

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `dist/index.module.js` | 2.26 kB | +50 B (2%) |  |

<details><summary>ℹ️ <strong>View Unchanged</strong></summary>

| Filename | Size | Change | |
|:--- |:---:|:---:|:---:|
| `./dist/index.css` | 485 B | 0 B |  |


</details>



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a

**Comment by omgovich** [comment]
Hey @RyanChristian4427!
This branch has a lot of conflicts since I merged the "Alpha support" branch.

**Comment by RyanChristian4427** [comment]
Got it, I'll get things corrected when I have the chance

**Comment by RyanChristian4427** [comment]
Should be good to go I think?

**Comment by omgovich** [comment]
Thanks @RyanChristian4427!

**Pull request merged**
