### PR TITLE
Make dynamic favicon that looks like a picker handle

### PR DESCRIPTION
**Pull request by molefrog**
Just got this crazy idea and decided to implement it. 
Screenshot 2020-08-13 at 18 21 13

### CODE REVIEW

**Comment by omgovich** [comment]
My God! That's so good, thanks!

I think we should spend some time on performance optimisations. It seems to me that image rendering (with shadow), tag removing and creating on each onChange may take a while on smartphones or/and low budget computers.

**Comment by omgovich** [comment]
@molefrog Check this out.

- Added `useThrottledEffect` with 500 ms interval. Browsers can't update favicon as fast as we update `color` anyway.
- The background (white circle and shadow) is cached as a separate canvas.
- Got rid of `document.getElementById`. Use `ref` to get the node.
- Render a favicon once if the screen width is less than 768.

**Comment by omgovich** [comment]
@molefrog I'm afraid that previous circles' edges will be visible because of antialiasing. So let's keep the current colution.

**Comment by molefrog** [comment]
> @molefrog I'm afraid that previous circles' edges will be visible because of antialiasing. So let's keep the current solution.

Same, ok let's keep it that way.

**Comment by omgovich** [comment]
Deployed: https://omgovich.github.io/react-colorful/

**Pull request merged**
